name: Bundle test

on:
  push: ~
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    name: With PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }} and ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest ]
        php: [ '7.4', '8.0', '8.1' ]
        symfony: ['4.4.*', '5.4.*', '6.0.*', '6.1.*']

        exclude:
          # excludes php 8+ symfony 4.4 on linux windows
          - operating-system: ubuntu-latest
            php: '8.0'
            symfony: '4.4.*'
          - operating-system: windows-latest
            php: '8.0'
            symfony: '4.4.*'
          - operating-system: ubuntu-latest
            php: '8.1'
            symfony: '4.4.*'
          - operating-system: windows-latest
            php: '8.1'
            symfony: '4.4.*'
          # excludes php 7.4 with symfony 6+
          - operating-system: ubuntu-latest
            php: '7.4'
            symfony: '6.0.*'
          - operating-system: windows-latest
            php: '7.4'
            symfony: '6.0.*'
          - operating-system: ubuntu-latest
            php: '7.4'
            symfony: '6.1.*'
          - operating-system: windows-latest
            php: '7.4'
            symfony: '6.1.*'
          # excludes php 8.0 with symfony 6.1+
          - operating-system: ubuntu-latest
            php: '8.0'
            symfony: '6.1.*'
          - operating-system: windows-latest
            php: '8.0'
            symfony: '6.1.*'

    steps:
      - uses: actions/checkout@master

      - name: Validate composer.json
        run: composer validate --strict

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex

      - name: Download dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        uses: ramsey/composer-install@v1

      - name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        run: composer run-script test

      - name: PHP-CS-FIXER test on ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        run: composer run-script fix
