name: Bundle test

on:
  push: ~
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ] #, windows-latest ]
        php: [ '7.4', '8.4' ]
    name: On ${{ matrix.operating-system }} with PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@master

      - name: Validate composer.json
        run: composer validate --strict

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json with ${{ matrix.php }}
        run: composer validate --strict

      - name: Cache Composer packages with ${{ matrix.php }}
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Minimum supported dependencies with the latest and PHP ${{ matrix.php }}
        run: composer update --prefer-dist --no-progress

      - name: Run test suite on PHP ${{ matrix.php }}
        run: composer run-script test
