name: Bundle test

on:
  push: ~
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest ]
        php: [ '7.4', '8.0', '8.1' ]
        symfony: ['4.4.*', '5.4.*', '6.0.*', '6.1.*']

        exclude:
          # excludes php 8+ symfony 4.4 on linux windows
          - operating-system: ubuntu-latest
            php: '8.0'
            symfony: '4.4.*'
          - operating-system: windows-latest
            php: '8.0'
            symfony: '4.4.*'
          - operating-system: ubuntu-latest
            php: '8.1'
            symfony: '4.4.*'
          - operating-system: windows-latest
            php: '8.1'
            symfony: '4.4.*'
          # excludes php 7.4 with symfony 6+
          - operating-system: ubuntu-latest
            php: '7.4'
            symfony: '6.0.*'
          - operating-system: windows-latest
            php: '7.4'
            symfony: '6.0.*'
          - operating-system: ubuntu-latest
            php: '7.4'
            symfony: '6.1.*'
          - operating-system: windows-latest
            php: '7.4'
            symfony: '6.1.*'


    name: With PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }} and ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@master

      - name: Validate composer.json
        run: composer validate --strict

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Echo PHP version
        run: php -v

      - name: Install symfony/flex
        run: composer global require --no-progress --no-scripts --no-plugins symfony/flex

      - name: Validate composer.json with ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        run: composer validate --strict

      - name: Cache Composer packages with ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-symfony-${{ matrix.symfony }}

      - name: Composer update with PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        run: SYMFONY_REQUIRE=${{ matrix.symfony }} composer update --prefer-dist --no-progress

      - name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        run: composer run-script test

      - name: PHP-CS-FIXER test on ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        run: composer run-script fix
